public enum Events 
{
    START_NEW_GAME,
    LOAD_GAME,
    WIN,
    PAUSE,
    RESET,

    START_HUD_TUTO,

    SWITCH_ROOM,
    ROOM_CLEARED,
    LOCK_CONNECTED_ROOMS,

    UNLOCK_CONTROLS,
    FADE_OUT,

    INITIALIZE_ENEMIES,
    ENEMY_SPAWNED,
    ENEMY_KILLED,

    PLAYER_DIED,
    PLAYER_TAKE_DAMAGE,
    PLAYER_STAMINA_CHANGE,
    PLAYER_HEALTH_CHANGE,
    PLAYER_COIN_CHANGE,
    PLAYER_WALKING,
    PLAYER_IDLE,
    PLAYER_CONSUMABLE,

    PLAYER_MOVEMENT,
    PLAYER_BASIC_ATTACK,
    PLAYER_CHARGE_ATTACK,
}